"""empty message

Revision ID: fb04ed2873ef
Revises: 
Create Date: 2023-06-12 19:41:11.352024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb04ed2873ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emanetler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('muddeti', sa.String(length=25), nullable=True),
    sa.Column('faizderecesi', sa.String(length=25), nullable=True),
    sa.Column('valyuta', sa.String(length=25), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emanetsorgu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=True),
    sa.Column('soyad', sa.String(length=100), nullable=True),
    sa.Column('nomre', sa.String(length=100), nullable=True),
    sa.Column('deposit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kampaniyalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=25), nullable=True),
    sa.Column('date1', sa.String(length=25), nullable=True),
    sa.Column('date2', sa.String(length=25), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('kategori', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onlinenovbe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filial', sa.String(length=100), nullable=True),
    sa.Column('xidmet_novu', sa.String(length=100), nullable=True),
    sa.Column('tarix', sa.String(length=100), nullable=True),
    sa.Column('vaxt', sa.String(length=100), nullable=True),
    sa.Column('mobil_nomre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slider1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('meblegi', sa.String(length=25), nullable=True),
    sa.Column('faizderecesi', sa.String(length=25), nullable=True),
    sa.Column('muddeti', sa.String(length=25), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slider2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('nagdlasdirma', sa.String(length=25), nullable=True),
    sa.Column('guzes', sa.String(length=25), nullable=True),
    sa.Column('kartlimit', sa.String(length=25), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('fin', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cins', sa.String(length=100), nullable=True),
    sa.Column('unvan', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xeberler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('image2', sa.String(length=255), nullable=True),
    sa.Column('image3', sa.String(length=255), nullable=True),
    sa.Column('image4', sa.String(length=255), nullable=True),
    sa.Column('kategori', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kartlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kartadi', sa.String(length=100), nullable=True),
    sa.Column('securty', sa.String(length=100), nullable=True),
    sa.Column('expires', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kartlar')
    op.drop_table('xeberler')
    op.drop_table('user')
    op.drop_table('slider2')
    op.drop_table('slider1')
    op.drop_table('onlinenovbe')
    op.drop_table('kampaniyalar')
    op.drop_table('emanetsorgu')
    op.drop_table('emanetler')
    op.drop_table('contact_us')
    # ### end Alembic commands ###
